name: Ci Build Testings

on:
  push:
    branches: [ 2nd_branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          architecture: x64

#      - name: Build with Maven Wrapper
#        run: mvn clean install
#      #      - name: Execute test using TestContainers
#      #        run: ./mvnw surefire:test -Dgroups="com.sdet.auto.groups.ContainersTest"

      - name: "sending variable to shell schript"

        run: chmod +x script1.sh
      - name: "pass variable"
        run: script1.sh hell


      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Build and Run Tests
        run: mvn test --batch-mode --fail-at-end
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1

