name: Java CI

on:
  push:
    branches: [ Branch_1]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven Wrapper
        run: mvn clean install
#      - name: Execute test using TestContainers
#        run: ./mvnw surefire:test -Dgroups="com.sdet.auto.groups.ContainersTest"
      - uses: test execution
      - name: mvn -Dtest=BaseTest
